### PR TITLE
Installable package

### PR DESCRIPTION
**Pull request by nickeopti**
Make the package `pip`-installable directly from the repository.

Add all the optional dependencies to the `pyproject.toml` file, rather than in the `requirements.txt` file, to allow installation by e.g.
```bash
pip install -e hyperiax[dev]
```

### CODE REVIEW

**Comment by nickeopti** [comment]
Sure about removing `tqdm`?

It is used in 
https://github.com/ComputationalEvolutionaryMorphometry/hyperiax/blob/main/hyperiax/mcmc/metropolis_hastings.py#L15
and imported (but unused) in
https://github.com/ComputationalEvolutionaryMorphometry/hyperiax/blob/main/hyperiax/execution/executor.py#L6

**Comment by frozaken** [comment]
Good point, its definitely a mistake its imported in the executor, however I wasn't aware that its included in MH. I generally like the idea of the library not printing or displaying anything, unless it is very explicitly requested (eg. plotting) - what do you think?

**Comment by nickeopti** [comment]
I think let's keep `tqdm` as a dependency for now, get this PR merged, and then remove `tqdm` once we've refactored the MH code. I haven't thought sufficiently much about the MCMC part of the code so far

**Comment by nickeopti** [comment]
Hmm, I'm not sure what just happened here... Hopefully nothing problematic. I'll check :thinking:

**Comment by nickeopti** [comment]
I believe this is alright again. Turns out you can sync individual branches between origin and forks -- I was not aware of that difference

**Pull request merged**
